services:
  - type: web
    name: GeneradorListas
    env: dotnet
    plan: free
    branch: main
    rootDir: .
    buildCommand: dotnet publish -c Release -o out
    startCommand: dotnet out/GeneradorListas.dll
    envVars:
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:10000
    ports:
      - 10000